# -*- coding: utf-8 -*-
"""ML Lab 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UxO240tfQJuGFO0n07KnUqAGRMeqFljH
"""

## ML Lab 4
## C_C1_02
## Saujanya Chaturvedi

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("WineQT.csv")

df.head()

df.info()

df.shape

df = pd.read_csv("WineQT.csv")

df.duplicated().sum()

df = df.drop_duplicates()

df.duplicated().sum()

sns.boxplot(data=df, color="deeppink"); plt.xticks(rotation=45); plt.show()

plt.plot(df.index, df["quality"], color="deeppink"); plt.xlabel("Index"); plt.ylabel("Quality"); plt.show()

plt.pie(df["quality"].value_counts(), labels=df["quality"].value_counts().index, autopct="%1.1f%%"); plt.show()

sns.countplot(x="quality", data=df, color="deeppink"); plt.show()

for col in df.drop("quality", axis=1).columns: sns.barplot(x=df["quality"], y=df[col], color="deeppink"); plt.show()

sns.scatterplot(x=df["fixed acidity"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["volatile acidity"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["citric acid"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["residual sugar"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["chlorides"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["free sulfur dioxide"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["total sulfur dioxide"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["density"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["pH"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["sulphates"], y=df["quality"], color="deeppink"); plt.show()
sns.scatterplot(x=df["alcohol"], y=df["quality"], color="deeppink"); plt.show()

sns.histplot(df["fixed acidity"], color="deeppink"); plt.show()
sns.histplot(df["volatile acidity"], color="deeppink"); plt.show()
sns.histplot(df["citric acid"], color="deeppink"); plt.show()
sns.histplot(df["residual sugar"], color="deeppink"); plt.show()
sns.histplot(df["chlorides"], color="deeppink"); plt.show()
sns.histplot(df["free sulfur dioxide"], color="deeppink"); plt.show()
sns.histplot(df["total sulfur dioxide"], color="deeppink"); plt.show()
sns.histplot(df["density"], color="deeppink"); plt.show()
sns.histplot(df["pH"], color="deeppink"); plt.show()
sns.histplot(df["sulphates"], color="deeppink"); plt.show()
sns.histplot(df["alcohol"], color="deeppink"); plt.show()

plt.figure(figsize=(12, 8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

Q1 = df.quantile(0.25, numeric_only=True)
Q3 = df.quantile(0.75, numeric_only=True)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:")
print(Q1)

print("\nQ3:")
print(Q3)

print("\nIQR:")
print(IQR)

print("\nLower Limit:")
print(lower_limit)

print("\nUpper Limit:")
print(upper_limit)

outliers = ((df < lower_limit) | (df > upper_limit)).sum()

print("Number of outliers:")
print(outliers)

print(outliers[outliers > 0])

df = df[~((df < lower_limit) | (df > upper_limit)).any(axis=1)]

print(df.shape)

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.inspection import permutation_importance

X = df.drop("quality", axis=1)
y = df["quality"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

results = []

def evaluate(name, model):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)

    print(name, acc)
    print(classification_report(y_test, pred))

    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

    plt.title(name)
    plt.show()

    results.append([name, acc, model.get_depth(), model.tree_.node_count])

    return model

tree = evaluate("Original", DecisionTreeClassifier(criterion="entropy", random_state=42))
plt.figure(figsize=(35,15))
plot_tree(tree, feature_names=X.columns, filled=True, max_depth=3)
plt.show()

plt.figure(figsize=(25,15))

plot_tree(
    tree,
    feature_names=X.columns,
    class_names=[str(1) for i in sorted (y.unique())],
    filled=True,
    rounded=True,
    fontsize=12,
    max_depth=3
)

plt.show()

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    criterion='entropy',
    random_state=42
)

dt_model.fit(X_train, y_train)

importance = pd.Series(dt_model.feature_importances_, index=X.columns).sort_values(ascending=False)

print(importance)

plt.figure(figsize=(10, 6))

importance.sort_values().plot(kind='barh')

plt.xlabel('Feature Importance')
plt.ylabel('Features')
plt.title('Decision Tree Feature Importance')

plt.show()

train_accuracy = dt_model.score(X_train, y_train)
test_accuracy = dt_model.score(X_test, y_test)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

for d in [2,3,4,5,None]:
  evaluate(f'MaxDepth=(d)', DecisionTreeClassifier(criterion='entropy',max_depth=d,random_state=42))

# Hyperparameter

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

param_grid = {
    'criterion': ['entropy'],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': [None, 'sqrt', 'log2'],
    'ccp_alpha': [0, 0.001, 0.005, 0.01]
}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters")
print(grid.best_params_)

print("Best Cross Validation Accuracy")
print(grid.best_score_)

best_tree = grid.best_estimator_

y_pred = best_tree.predict(X_test)

print(classification_report(y_test,y_pred))
print("Accuracy =",accuracy_score(y_test,y_pred))

# Cross Validation

from sklearn.model_selection import cross_val_score

scores = cross_val_score(best_tree, X, y, cv=10, scoring='accuracy')

print(scores)
print("Average Accuracy =", scores.mean())
print("Std =", scores.std())

# Learning Curve

from sklearn.model_selection import learning_curve
import matplotlib.pyplot as plt

train_sizes, train_scores, test_scores = learning_curve(
    best_tree, X, y, cv=5, scoring="accuracy"
)

plt.figure(figsize=(8, 5))

plt.plot(
    train_sizes,
    train_scores.mean(axis=1),
    marker='o',
    label='Training Accuracy'
)

plt.plot(
    train_sizes,
    test_scores.mean(axis=1),
    marker='o',
    label='Validation Accuracy'
)

plt.xlabel("Training Size")
plt.ylabel("Accuracy")
plt.title("Learning Curve")
plt.legend()

plt.show()

# Validation Curve

from sklearn.model_selection import validation_curve
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

param_range = [2, 3, 4, 5, 6, 7, 8, 9, 10]

train_score, test_score = validation_curve(
    DecisionTreeClassifier(criterion='entropy', random_state=42),
    X,
    y,
    param_name="max_depth",
    param_range=param_range,
    cv=5
)

plt.plot(param_range, train_score.mean(axis=1), label='Training')
plt.plot(param_range, test_score.mean(axis=1), label='Validation')

plt.legend()
plt.xlabel("Max Depth")
plt.ylabel("Accuracy")
plt.show()

# Normalised Confusion Matrix

cm = confusion_matrix(y_test, y_pred)

cm_percent = cm / cm.sum(axis=1, keepdims=True)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_percent,
    annot=True,
    fmt=".2%",
    cmap="RdPu"
)

plt.title("Confusion Matrix (%)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

